program: training.py
name: "with_cross_val_size_600_500"
method: grid
metric:
  goal: minimize
  name: test_loss
parameters:
  transform:
    values: ['none', 'random_erasing_delete', "random_erasing_random", "random_crop","random_horizontal_flip","random_vertical_flip", "random_rotation", "color_jitter",  "random_noise(0.4, 0.5)", "random_noise(0, 0.1)" ]
  fold:
    values: ['fold_0', 'fold_1', 'fold_2', 'fold_3', 'fold_4']
  batch_size:
    values: [64]
image_size:
  height: 600
  width: 500
folds_path: "metadata_folds/kkui-lung-bline-lumify:latest/video"
optimizer: "adam"
learning_rate: 0.0001
criterion: "cross-entropy"
img_dir: ""
fc_layer_size: 512
number_of_classes: 2
patience: 5
epochs: 30