arch: resnet18
comment: ''
criterion: cross-entropy
device: cuda
dropout: false
dropout_rate: 0.8
early_stopping: true
epochs: 40
experiment_class: b_line
fc_layer_size: 512
folds_path: metadata_folds/kkui-lung-bline-lumify:latest/video
img_dir: /home/vn126ks/nas_storage_synology/APVV_Lung/revision_8/
init_transform:
- CT.TransformResize((600, 400))
- CT.TransformPad((600, 400))
is_validating: true
learning_rate: 0.0001
method: grid
metric:
  goal: minimize
  name: val_f1
name: with_cross_val_with_aug
number_of_classes: 2
optimizer: adam
output_transform: none
parameters:
  batch_size:
    values:
    - 32
  fold:
    values:
    - fold_0
    - fold_1
    - fold_2
    - fold_3
    - fold_4
  transform:
    values:
    - - None
    - - MT.RandGridDistortion(num_cells=5, prob=0.5, distort_limit=(-0.03, 0.03))
    - - MT.RandGridDistortion(num_cells=5, prob=0.5, distort_limit=(-0.09, 0.09))
    - - MT.RandGridDistortion(num_cells=5, prob=0.5, distort_limit=(-0.1, 0.1))
    - - MT.RandGridDistortion(num_cells=5, prob=0.5, distort_limit=(-0.3, 0.3))
    - - MT.RandGridDistortion(num_cells=5, prob=0.5, distort_limit=(-0.5, 0.5))
    - - MT.RandGridDistortion(num_cells=3, prob=0.5, distort_limit=(-0.03, 0.03))
    - - MT.RandGridDistortion(num_cells=3, prob=0.5, distort_limit=(-0.09, 0.09))
    - - MT.RandGridDistortion(num_cells=3, prob=0.5, distort_limit=(-0.1, 0.1))
    - - MT.RandGridDistortion(num_cells=3, prob=0.5, distort_limit=(-0.3, 0.3))
    - - MT.RandGridDistortion(num_cells=3, prob=0.5, distort_limit=(-0.5, 0.5))
    - - MT.RandGridDistortion(num_cells=7, prob=0.5, distort_limit=(-0.03, 0.03))
    - - MT.RandGridDistortion(num_cells=7, prob=0.5, distort_limit=(-0.09, 0.09))
    - - MT.RandGridDistortion(num_cells=7, prob=0.5, distort_limit=(-0.1, 0.1))
    - - MT.RandGridDistortion(num_cells=7, prob=0.5, distort_limit=(-0.3, 0.3))
    - - MT.RandGridDistortion(num_cells=7, prob=0.5, distort_limit=(-0.5, 0.5))
    - - MT.RandGridDistortion(num_cells=9, prob=0.5, distort_limit=(-0.03, 0.03))
    - - MT.RandGridDistortion(num_cells=9, prob=0.5, distort_limit=(-0.09, 0.09))
    - - MT.RandGridDistortion(num_cells=9, prob=0.5, distort_limit=(-0.1, 0.1))
    - - MT.RandGridDistortion(num_cells=9, prob=0.5, distort_limit=(-0.3, 0.3))
    - - MT.RandGridDistortion(num_cells=9, prob=0.5, distort_limit=(-0.5, 0.5))
  yaml_file:
    values:
    - sweep_grid_distortion_single.yaml
patience: 5
pretrained: true
program: training.py
save_weights: true
saving_only_best_one_weight_val_loss: true
testing_with_best_val_loss: true
val_dist: 0.2
weights_dir: /home/vn126ks/nas_storage_synology/_experiments_output/weights/
