program: training.py
name: "with_cross_val_with_aug"
method: grid

# Metric to optimize
metric:
  goal: minimize
  name: val_f1

# Hyperparameters
parameters:
  transform:
    values:
      - "None"
      - "RandAffine(prob=0.5, mode='bilinear', shear_range=0.261799)"
      - "RandAffine(prob=0.5, mode='nearest', shear_range=0.261799)"
      -




  fold:
    values: ['fold_0', 'fold_1', 'fold_2', 'fold_3', 'fold_4']
  batch_size:
    values: [32]
  yaml_file:
    values: ["sweep_combined_gpu.yaml"]

# Paths and directories
folds_path: "metadata_folds/kkui-lung-bline-lumify:latest/video"
img_dir: "/home/vn126ks/nas_storage_synology/APVV_Lung/revision_8/"
weights_dir: "/home/vn126ks/nas_storage_synology/_experiments_output/weights/"

# Model configuration
optimizer: "adam"
learning_rate: 0.0001
criterion: "cross-entropy"
fc_layer_size: 512
number_of_classes: 2
device: "cuda"
arch: "resnet18"
pretrained: True
dropout: False
dropout_rate: 0.8


# Training process
patience: 5
early_stopping: True
epochs: 40
is_validating: True
val_dist: 0.2
save_weights: True

# Testing process
testing_with_best_val_loss: True
saving_only_best_one_weight_val_loss: True

# Transformations
init_transform: ["TransformResize(600)", "TransformPad(600)"]
output_transform: "none"

# Experiment details
experiment_class: "b_line"
comment: ""