wandb_version: 1

program:
  desc: null
  value: training_sweep.py
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: minimize
    name: val_loss
parameters:
  desc: null
  value:
    transform:
      values:
      - none
      - random_erasing
      - random_crop
      - random_horizontal_flip
      - random_vertical_flip
      - random_rotation
    batch_size:
      values:
      - 32
      - 64
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708432195.997277
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.11.7
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 32
transform:
  desc: null
  value: random_rotation
