program: training.py
name: "with_cross_val"
method: grid

# Metric to optimize
metric:
  goal: minimize
  name: val_f1

# Hyperparameters
parameters:
  transform:
    values:
      - - "RandomResizedCrop(510)"
        - "RandomVerticalFlip()"
        - "RandomRotation(degrees=15)"
        - "ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1)"
        - "RandomAffine(degrees=15, translate=(0.1, 0.1), scale=(0.8, 1.2), shear=10)"
        - "Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))"
  fold:
    values: ['fold_0', 'fold_1', 'fold_2', 'fold_3', 'fold_4']
  batch_size:
    values: [64]
  yaml_file:
    values: ["configs/sweep.yaml"]

# Paths and directories
folds_path: "metadata_folds/kkui-lung-bline-lumify:latest/video"
img_dir: "/Volumes/LaCie/Macbook/Bachelor/Practical/"

# Model configuration
optimizer: "adam"
learning_rate: 0.0001
criterion: "cross-entropy"
fc_layer_size: 512
number_of_classes: 2
device: "mps"
arch: "resnet18"
pretrained: True
dropout: False
dropout_rate: 0.8


# Training process
patience: 5
early_stopping: True
epochs: 5
is_validating: True
val_dist: 0.2
save_weights: True
weights_dir: "weights/"

# Testing process
testing_with_best_val_loss: True
saving_only_best_one_weight_val_loss: True

# Transformations
init_transform: ["TransformResize(600)", "TransformPad(600)"]
output_transform: "none"

# Experiment details
experiment_class: "b_line"
comment: ""