wandb_version: 1

mode:
  desc: null
  value: r
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710768852.881804
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.11.0
      5: 0.16.3
      6: 4.32.1
      8:
      - 4
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 64
fold:
  desc: null
  value: fold_1
transform:
  desc: null
  value: color_jitter
